-- =================================================================================
-- FASE 1: BLINDAJE DE SEGURIDAD (ANTI-TROLLS)
-- =================================================================================
-- Limitar la caducidad máxima a 14 días para evitar fechas absurdas.
ALTER TABLE public.locations DROP CONSTRAINT IF EXISTS check_valid_expiration;
ALTER TABLE public.locations
ADD CONSTRAINT check_valid_expiration 
CHECK (
  expires_at IS NULL OR 
  (expires_at >= NOW() - INTERVAL '1 hour' AND expires_at <= NOW() + INTERVAL '14 days')
);

-- =================================================================================
-- FASE 2: CANAL TÁCTICO (LA CAMPANA) Y LIMPIEZA PARASITARIA
-- =================================================================================

-- 1. Tabla de alertas tácticas
CREATE TABLE IF NOT EXISTS public.tactical_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL,
    location_id text,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    created_at timestamptz DEFAULT NOW()
);

-- 2. Habilitar Realtime para la campana
ALTER PUBLICATION supabase_realtime ADD TABLE public.tactical_alerts;

-- 3. Políticas de seguridad (Solo lectura pública, inserción vía RPC si es necesario)
ALTER TABLE public.tactical_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tactical_alerts_select_policy" ON public.tactical_alerts;
CREATE POLICY "tactical_alerts_select_policy" ON public.tactical_alerts FOR SELECT USING (true);

-- 4. Función de limpieza parasitaria
CREATE OR REPLACE FUNCTION public.cleanup_old_tactical_alerts()
RETURNS TRIGGER AS $$
BEGIN
    -- Borra silenciosamente alertas con más de 48 horas de antigüedad
    DELETE FROM public.tactical_alerts WHERE created_at < NOW() - INTERVAL '48 hours';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Trigger parasitario
DROP TRIGGER IF EXISTS tactical_parasite_trigger ON public.tactical_alerts;
CREATE TRIGGER tactical_parasite_trigger
AFTER INSERT ON public.tactical_alerts
FOR EACH STATEMENT
EXECUTE FUNCTION public.cleanup_old_tactical_alerts();

-- =================================================================================
-- FASE 3: CONECTAR EVENTOS (Cuando se crea un centro, dispara una alerta táctica)
-- =================================================================================
CREATE OR REPLACE FUNCTION public.add_location_secure(
    p_name text,
    p_type text,
    p_needs text,
    p_address text,
    p_lat double precision,
    p_lng double precision,
    p_leader_name text,
    p_leader_phone text,
    p_auth_code text,
    p_expires_at timestamptz DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
    new_loc_id uuid;
BEGIN
    IF p_auth_code != 'SOS-VZLA-2026' THEN
        RAISE EXCEPTION 'Código de autorización inválido';
    END IF;

    INSERT INTO public.locations (
        name, type, needs, address, lat, lng,
        leader_name, leader_phone, is_active, updated_at, expires_at
    ) VALUES (
        p_name, p_type, p_needs, p_address, p_lat, p_lng,
        p_leader_name, p_leader_phone, true, NOW(), p_expires_at
    ) RETURNING id INTO new_loc_id;

    -- Disparar alerta táctica
    INSERT INTO public.tactical_alerts (title, description, location_id, lat, lng)
    VALUES (
        'Nuevo Centro: ' || p_name,
        'Se requiere apoyo en ' || COALESCE(p_address, 'ubicación aproximada'),
        new_loc_id::text, p_lat, p_lng
    );
END;
$$;
